# Generated by Django 4.1.5 on 2023-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_edited_time'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['blog'], name='posts_post_blog_id_dbe9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['title'], name='posts_post_title_e7697c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content'], name='posts_post_content_3c9fae_idx'),
        ),
    ]
