# Generated by Django 4.1.5 on 2023-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author'], name='blogs_blog_author__166d94_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='blogs_blog_title_1d12f9_idx'),
        ),
    ]
